[package]
name = "aoc2024"
version = "0.1.0"
edition = "2021"
include = ["/src"]

[dependencies]
itertools = "0.13.0"
memoize = "0.4.2"
ndarray = "0.16.1"
pest = "2.7.14"
pest_derive = "2.7.14"
petgraph = "0.6.5"
rand = "0.8.5"
regex = "1.11.1"
rustc-hash = "2.1.0"


#[profile.release]
#debug=true
